# Generated by Django 4.1.2 on 2022-11-03 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martle_app_backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_img_upload',
            field=models.ImageField(default=None, upload_to='product_images'),
        ),
    ]
