# Generated by Django 4.1.2 on 2022-11-03 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('martle_app_backend', '0002_remove_product_product_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='product_img_upload',
            new_name='product_img_file',
        ),
    ]
