# Generated by Django 4.1.2 on 2022-10-29 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('martle_app_backend', '0003_rename_post_comment_product_customer_zipcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='zipcode',
            field=models.IntegerField(),
        ),
    ]
