# Generated by Django 4.1.2 on 2022-11-03 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('martle_app_backend', '0004_alter_productimage_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='product_image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='martle_app_backend.product'),
        ),
    ]
