# Generated by Django 4.1.13 on 2024-02-21 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martle_app_payment", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martlet",
            name="martle_bank",
            field=models.FloatField(default=500000),
        ),
        migrations.AlterField(
            model_name="martlet",
            name="martle_pay",
            field=models.FloatField(default=0),
        ),
    ]
