# Generated by Django 4.1.13 on 2024-02-11 23:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martle_recommendation_system", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinteraction",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
