# Generated by Django 4.1.13 on 2024-02-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("martle_recommendation_system", "0002_alter_userinteraction_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinteraction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
